### ISSUE TITLE
Emoji looks too large when export PDF by dw2pdf 

### ISSUE THREAD

**Issue by bossyang** [ptbrown/dokuwiki-plugin-emoji#2]
The emoji looks great in web browser. It looks good when _print_ web page to pdf, too. It seems to keep original size in pdf by **dw2pdf** plugin. Is this an issue of dw2pdf?

**Comment by ptbrown** [comment]
Thanks. I'm looking into it. To be sure, can you provide a PDF demonstrating the problem?

**Comment by ptbrown** [comment]
Okay, it was my fault. Dw2pdf doesn't see the external stylesheet. And there isn't a trigger where I can tell the CSS compiler how to find it. The solution is to move the styles into a standard DokuWiki location. That isn't much of a problem since I stopped using the sprite icons which had a much larger CSS definition.

The new plugin will be uploaded in a few hours.

**Comment by ptbrown** [comment]
@bossyang Can you please test that your problem is solved with the latest commit?

**Comment by bossyang** [comment]
@ptbrown It works! Thank you.
